### ISSUE TITLE
Regarding  configuration with stm32

### ISSUE THREAD

**Issue by parth-6** [mcmchris/mcm-grove-voltage-sensor#2]
Is it possible to configure this Library to work with stm32- Nucleo boards .
I want to use 3 of these sensors to calculate the Ac voltage across the application . 
I want to use this sensor with arm cortex m4 stm32 boards.
I reside in India and we have,the voltage in India is 220 volts, alternating at 50 cycles (Hertz) per second.
so what modification should i make to this library. And what parameters should i use in my project?

**Comment by mcmchris** [comment]
Hi @parth-6 thanks for asking.

If you are using the STM32 board support package for the Arduino IDE, the library can be used without problem.

If you are using any other programming environment for the STM32, you can see the **calcVI** function in this [project](https://github.com/mcmchris/Appliances-Identifier-Smart-Energy-Meter/blob/master/main.cpp) I made using a STM32F767ZI.

The module needs no modification to work with 220 VAC and 50 Hz. 
You can follow this [colleague's video guide](https://www.youtube.com/watch?v=gxvkHMCZ1Jc) showing how to use my sensor with 220 VAC.

**Comment by parth-6** [comment]
"I reside in India and we have,the voltage in India is 220 volts, alternating at 50 cycles (Hertz) per second."
there is update regarding this , actually in my location the voltage rating is 240 Vac, it may some times vary upto 250 also , so will this work in those condition?

**Comment by mcmchris** [comment]
Sure, with no problem. @parth-6

**Comment by parth-6** [comment]
As mention in prior i trying to use this sensor with stm32 to do so , will this library work in stm32cubeide, also i want to use wcs1700 hall effect current sensor to measure AC rms current value , so how can i do so?
